import Link from 'next/link';
import { ArrowRight, Globe2, ScanLine, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { ServicePreview } from '@/components/service-preview';
import { ArchitectureDiagram } from '@/components/architecture-diagram';

export default function Home() {
  return <>
    <section className="section-shell grid items-center gap-12 pb-16 pt-14 sm:pb-24 sm:pt-20 lg:grid-cols-[1.08fr_1fr]">
      <div><p className="eyebrow">ENS402 / A name to resolve. A payment to verify.</p><h1 className="mt-7 text-[clamp(3.1rem,5.7vw,5.3rem)] font-medium leading-[1.04] tracking-[-.06em]">Let agents find<br/>services.<br/><span className="text-primary">Verify where<br/>they pay.</span></h1>
        <p className="mt-7 max-w-lg text-lg leading-relaxed text-muted-foreground">An API tells your agent how to pay. ENS402 checks that request against the merchant&apos;s public ENS settings before asking your wallet to sign.</p>
        <div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><a href="#stack">See how it works <ArrowRight aria-hidden="true"/></a></Button><Button asChild variant="outline" size="lg"><Link href="/architecture">Architecture & evidence</Link></Button></div>
        <p className="mt-6 text-xs leading-6 text-muted-foreground">Built for agent developers · Privy is the demo signer · Use your own wallet adapter</p>
      </div><ServicePreview/>
    </section>
    <section className="border-y bg-card/40"><div className="section-shell grid gap-5 py-10 md:grid-cols-[.8fr_1.2fr] md:gap-16"><h2 className="text-2xl font-medium tracking-tight">Permission to buy a service<br/>should have a clear destination.</h2><div><p className="text-sm leading-7 text-muted-foreground">Your agent buys a search result for $0.01. Tomorrow, the same API asks it to pay a different wallet. Was that a Treasury update, a mistake, or a compromised server?</p><p className="mt-3 text-sm leading-7 text-foreground">ENS gives the agent an independent place to check. Native ENSv2 permissions let the merchant keep API updates and payment changes under different keys.</p></div></div></section>
    <section id="stack" className="section-shell py-20 sm:py-24"><p className="eyebrow">01 / Before your agent signs</p><h2 className="mt-4 text-4xl font-medium tracking-tight">Find the service. Check the bill.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{[
      { title: 'Resolve the name', Icon: Globe2, text: 'Read the current API URL from ENS. A merchant can move its service without asking every client to change a hardcoded address.' },
      { title: 'Verify the request', Icon: ShieldCheck, text: 'Compare the requested recipient, token and network with ENS. Check the price and API URL against the buyer’s approval.' },
      { title: 'Screen the recipient', Icon: ScanLine, text: 'Ask Intercepta for known address risks. Reuse fresh evidence. Stop if it reports a blocking risk or cannot return a usable result.' },
    ].map(({ title, Icon, text }) => <Card key={title} className="shadow-none"><CardContent className="p-6"><Icon className="size-5 text-primary" aria-hidden="true"/><h3 className="mt-5 text-xl font-medium">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></CardContent></Card>)}</div><ArchitectureDiagram/></section>
    <section id="permissions" className="border-y bg-card/40"><div className="section-shell grid gap-10 py-20 lg:grid-cols-2 lg:gap-16"><div><p className="eyebrow">02 / Why ENSv2 permissions matter</p><h2 className="mt-4 text-4xl font-medium leading-tight tracking-tight">Give an agent the URL key.<br/><span className="text-primary">Keep the money key.</span></h2><p className="mt-6 text-sm leading-7 text-muted-foreground">A merchant lets its operations agent publish a new API URL. Treasury keeps permission to edit the payment record. These permissions are checked by the ENS resolver contract whenever someone tries to write.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">If the API server is compromised, its payment request still has to match the separately controlled ENS record.</p></div>
      <div className="divide-y rounded-xl border bg-background">{[
        ['Move the API', 'The operator updates only the endpoint record. Buyers resolve the new URL and check whether it is inside their approved scope.'],
        ['Try to redirect revenue', 'An endpoint-only operator cannot edit the payment record on the tested resolver. A mismatching HTTP 402 is rejected by the client.'],
        ['Rotate Treasury', 'Treasury publishes a new recipient. Existing buyer approval no longer matches, so the client asks for a new approval.'],
        ['Revoke an operator', 'Remove its applicable write permissions. The last published URL stays readable until an authorized writer changes it.'],
      ].map(([title, body]) => <div key={title} className="p-5"><h3 className="text-sm font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></div>)}</div>
    </div></section>
    <section id="integrate" className="section-shell grid gap-10 py-20 lg:grid-cols-2 lg:gap-16"><div><p className="eyebrow">03 / Fits the agent you already have</p><h2 className="mt-4 text-4xl font-medium tracking-tight">Keep your discovery.<br/>Connect your signer.</h2><p className="mt-6 text-sm leading-7 text-muted-foreground">Your agent chooses a service. ENS402 checks its resolved configuration and payment request, then returns a decision with risk evidence. The reusable Privy adapter connects to your own account.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">The demo defaults to Privy. Its policy is designed to limit the chain, token, recipient, amount per payment, and authorization expiry. ENS controls merchant records; Privy controls the signatures its wallet issues.</p><Button asChild variant="outline" className="mt-6"><Link href="/architecture#signing">See exactly what is enforced <ArrowRight aria-hidden="true"/></Link></Button></div>
      <div className="rounded-xl border bg-card p-6"><p className="eyebrow">The integration in plain English</p><ol className="mt-6 space-y-6">{[
        ['Choose', 'Bring a service name from your catalog, Bazaar, or your agent’s search.'],
        ['Check', 'Supply freshly resolved ENS records, the HTTP 402, and the buyer’s approved limits.'],
        ['Sign', 'Only matching requests with usable risk evidence reach the configured wallet.'],
        ['Pay', 'Use the resulting x402 authorization to request the paid resource and verify settlement.'],
      ].map(([title, body], i) => <li key={title} className="flex gap-4"><span className="font-mono text-sm text-primary">0{i + 1}</span><div><h3 className="text-sm font-medium">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{body}</p></div></li>)}</ol><p className="mt-6 border-t pt-4 text-xs leading-6 text-muted-foreground">Current implementation produces an authorization. Live ENS deployment and settlement are the next integration gates. Daily spending totals require a separate budget system.</p></div>
    </section>
    <section className="border-t bg-card/40"><div className="section-shell py-14"><p className="eyebrow">What we can show today</p><div className="mt-5 grid gap-6 md:grid-cols-3"><div><h2 className="font-medium">Native ENS permission checks</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Endpoint-only grants, rejected payment edits, revocation and root overrides exercised on an isolated Sepolia fork.</p></div><div><h2 className="font-medium">Real Intercepta response</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A genuine address scan returned toxicScore 0 and no traits. SDK checks cover provider failures and stale evidence.</p></div><div><h2 className="font-medium">Privy adapter implemented</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Tested with the official SDK and x402 signing format. Live provider policy enforcement awaits app credentials.</p></div></div><Link href="/architecture#status" className="mt-6 inline-flex items-center gap-2 text-sm text-primary">Evidence, remaining gates and sponsor Q&A <ArrowRight className="size-4" aria-hidden="true"/></Link></div></section>
  </>;
}
