'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, CheckCircle2, Loader2, RefreshCw, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { ResolvedService, EnsTransaction } from '@ens402/sdk/ens';
import type { Approval } from '@ens402/sdk';
import type { PaymentReceipt } from '@ens402/sdk/http';

type ApprovalRow = { id: string; service: ResolvedService; approval: Approval; daily_limit: string; state: string; payer: string | null };
type Execution = { id: string; approval_id: string; state: string; receipt: PaymentReceipt | null; created_at: string };
type State = { names: string[]; approvals: ApprovalRow[]; executions: Execution[] };
type Provider = { request(args: { method: string; params?: unknown[] }): Promise<unknown> };
const field = 'mt-2 w-full rounded-md border bg-background px-3 py-2.5 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50';
function units(value: string) { if (!/^\d+(\.\d{1,6})?$/.test(value)) throw new Error('Enter USDC with at most six decimal places.'); const [whole, fraction = ''] = value.split('.'); return String(BigInt(whole!) * 1000000n + BigInt(fraction.padEnd(6,'0'))); }
function usdc(value: string) { const n = BigInt(value); return `${n / 1000000n}.${String(n % 1000000n).padStart(6,'0').replace(/0+$/,'') || '0'}`; }
export function OperatorConsole() {
  const [token,setToken] = useState(''); const [connected,setConnected] = useState(false);
  const [setup,setSetup] = useState<{ name:string; configured:boolean }[]>([]);
  const [state,setState] = useState<State>({ names:[],approvals:[],executions:[] });
  const [name,setName] = useState(''); const [service,setService] = useState<ResolvedService | null>(null);
  const [endpoints,setEndpoints] = useState(''); const [limit,setLimit] = useState('0.01'); const [daily,setDaily] = useState('1'); const [hours,setHours] = useState('24');
  const [busy,setBusy] = useState(''); const [error,setError] = useState(''); const [notice,setNotice] = useState('');
  const [approvalKey,setApprovalKey] = useState(''); const [attempt,setAttempt] = useState<{id:string;approvalId:string} | null>(null);
  const [balances,setBalances] = useState<Record<string,string>>({}); const [seller,setSeller] = useState('');
  const [record,setRecord] = useState('agent-endpoint[x402]'); const [operation,setOperation] = useState('set'); const [value,setValue] = useState(''); const [operator,setOperator] = useState('');
  const [plan,setPlan] = useState<{ transaction:EnsTransaction; broadTextPermission:boolean; note:string } | null>(null);
  const [reconcileId,setReconcileId] = useState(''); const [tx,setTx] = useState('');
  useEffect(() => { fetch('/api/status').then(r=>r.json()).then(data=>setSetup(data.configured)).catch(()=>setError('Cannot load setup status.')); try { const stored = sessionStorage.getItem('ens402-pending-attempt'); if (stored) setAttempt(JSON.parse(stored)); } catch {} },[]);
  async function api<T>(body: Record<string,unknown>): Promise<T> {
    const response = await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed.'); return data as T;
  }
  async function refresh() { const data = await api<State>({action:'state'}); setState(data); setName(previous=>previous || data.names[0] || ''); }
  async function run(label:string, action:()=>Promise<void>) { setBusy(label);setError('');setNotice('');try { await action(); } catch(e) { setError(e instanceof Error ? e.message : 'Operation failed.'); } finally { setBusy(''); } }
  async function login(event:FormEvent) { event.preventDefault(); await run('connect',async()=>{await refresh();setConnected(true);}); }
  async function inspect() { await run('inspect',async()=>{const result=await api<ResolvedService>({action:'inspect',name});setService(result);setEndpoints(result.endpoint);setValue(result.endpoint);setApprovalKey(crypto.randomUUID());setPlan(null);}); }
  async function approve(event:FormEvent) { event.preventDefault(); await run('approve',async()=>{if(!service) return; await api({action:'approve',id:approvalKey,name:service.name,authority:service.authority,payTo:service.payment.payTo,endpoints:endpoints.split('\n').map(s=>s.trim()).filter(Boolean),maxAmount:units(limit),dailyLimit:units(daily),durationSeconds:Number(hours)*3600});await refresh();setNotice('Approval created. Fund its Privy wallet with Base Sepolia USDC before purchasing.');setApprovalKey(crypto.randomUUID());}); }
  async function buy(approvalId:string) { await run('purchase',async()=>{const current=attempt?.approvalId===approvalId?attempt:{id:crypto.randomUUID(),approvalId};setAttempt(current);sessionStorage.setItem('ens402-pending-attempt',JSON.stringify(current));const result=await api<Execution>({action:'execute',...current});await refresh();if(!['reserved','submitting','uncertain'].includes(result.state)){setAttempt(null);sessionStorage.removeItem('ens402-pending-attempt');}setNotice(result.receipt?.reason || 'Attempt recorded. Inspect its status before retrying.');}); }
  function wallet():Provider { const provider=(window as unknown as {ethereum?:Provider}).ethereum;if(!provider)throw new Error('Open this page in a browser with an Ethereum wallet to manage ENS.');return provider; }
  async function connectSeller() { await run('seller',async()=>{const provider=wallet();await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0xaa36a7'}]});const accounts=await provider.request({method:'eth_requestAccounts'}) as string[];setSeller(accounts[0] || '');setPlan(null);}); }
  async function prepare(event:FormEvent) { event.preventDefault();await run('prepare',async()=>{setPlan(null);setPlan(await api({action:'ens',operation,name,from:seller,key:record,value,operator}));}); }
  async function sendEns() { await run('send-ens',async()=>{if(!plan)return;const provider=wallet();if(await provider.request({method:'eth_chainId'})!=='0xaa36a7')throw new Error('Switch your wallet to Sepolia.');const accounts=await provider.request({method:'eth_accounts'}) as string[];if(accounts[0]?.toLowerCase()!==seller.toLowerCase())throw new Error('Wallet account changed. Connect and simulate again.');const hash=await provider.request({method:'eth_sendTransaction',params:[{from:seller,to:plan.transaction.to,data:plan.transaction.data,value:'0x0'}]});setNotice(`ENS transaction submitted: ${String(hash)}. Wait for confirmation, then inspect the service again.`);setPlan(null);}); }
  const pending = state.executions.some(e=>['reserved','submitting','uncertain'].includes(e.state));
  return <div className="section-shell py-12 sm:py-16"><p className="eyebrow">ENS402 / operator console</p><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-medium tracking-tight">From a service name<br/><span className="text-primary">to a verified payment.</span></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">Real provider operations on Sepolia and Base Sepolia. Review an approval before creating its wallet, then fund that wallet and make a purchase.</p></div><Badge variant="outline">Testnets only</Badge></div>
    <details className="mt-8 rounded-xl border bg-card p-5" open={setup.some(s=>!s.configured)}><summary className="cursor-pointer text-sm font-medium">Server setup · {setup.filter(s=>s.configured).length}/{setup.length} variables present</summary><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{setup.map(item=><p key={item.name} className="flex items-center gap-2 font-mono text-xs"><span className={item.configured?'text-primary':'text-muted-foreground'}>{item.configured?'✓':'○'}</span>{item.name}</p>)}</div><p className="mt-4 text-xs leading-6 text-muted-foreground">Presence is not a live provider check. Database migration, a controlled ENS name and wallet funding are also required. Read SETUP.md in the repository.</p></details>
    <div aria-live="polite" className="mt-5 space-y-3">{busy&&<p className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" aria-hidden="true"/>Working: {busy}</p>}{error&&<p role="alert" className="rounded-lg border border-destructive/40 p-4 text-sm text-destructive">{error}</p>}{notice&&<p className="break-all rounded-lg border border-primary/30 p-4 text-sm text-primary">{notice}</p>}</div>
    {!connected?<form onSubmit={login} className="mt-8 max-w-lg rounded-xl border p-6"><h2 className="text-xl font-medium">Open your demo workspace</h2><label className="mt-5 block text-sm">Demo access token<input type="password" autoComplete="off" className={field} value={token} onChange={e=>setToken(e.target.value)} minLength={32} required/></label><p className="mt-2 text-xs leading-6 text-muted-foreground">Use DEMO_ACCESS_TOKEN from your server setup. Never enter a Privy app secret here. This token is kept in memory only.</p><Button className="mt-5" disabled={!!busy}>Connect workspace <ArrowRight aria-hidden="true"/></Button></form>:<>
    <section className="mt-10"><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-medium">1. Inspect the service</h2><Button variant="outline" disabled={!!busy} onClick={()=>run('refresh',refresh)}><RefreshCw aria-hidden="true"/>Refresh activity</Button></div><div className="mt-5 flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-sm">Configured ENS service<select className={field} value={name} onChange={e=>{setName(e.target.value);setService(null);setPlan(null);}}>{state.names.map(n=><option key={n}>{n}</option>)}</select></label><Button disabled={!!busy||!name} onClick={inspect}>Resolve and inspect</Button></div>{service&&<Card className="mt-5"><CardContent className="grid gap-5 p-6 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Current API URL</p><p className="mt-2 break-all text-sm">{service.endpoint}</p></div><div><p className="text-xs text-muted-foreground">USDC recipient · Base Sepolia</p><p className="mt-2 break-all font-mono text-xs">{service.payment.payTo}</p></div><div><p className="text-xs text-muted-foreground">Native resolver · Sepolia block {service.block}</p><p className="mt-2 break-all font-mono text-xs">{service.resolver}</p></div><div><p className="text-xs text-muted-foreground">Registered owner · {service.status}</p><p className="mt-2 break-all font-mono text-xs">{service.owner}</p></div></CardContent></Card>}</section>
    {service&&<section className="mt-10"><h2 className="text-2xl font-medium">2. Approve a purchase scope</h2><form onSubmit={approve} className="mt-5 rounded-xl border bg-card p-6"><label className="block text-sm">Approved API URLs, one per line<textarea className={`${field} min-h-24 font-mono text-xs`} value={endpoints} onChange={e=>{setEndpoints(e.target.value);setApprovalKey(crypto.randomUUID());}} required/></label>{service.endpoint.endsWith('/api/merchant/search')&&<Button type="button" variant="ghost" className="mt-2" onClick={()=>{const next=new URL('/api/merchant/search-v2',service.endpoint).href;setEndpoints(text=>text.includes(next)?text:`${text}\n${next}`);setApprovalKey(crypto.randomUUID());}}>Also approve the demo v2 route</Button>}<div className="mt-5 grid gap-5 sm:grid-cols-3"><label className="text-sm">USDC per payment<input className={field} value={limit} inputMode="decimal" onChange={e=>{setLimit(e.target.value);setApprovalKey(crypto.randomUUID());}} required/></label><label className="text-sm">USDC per day, UTC<input className={field} value={daily} inputMode="decimal" onChange={e=>{setDaily(e.target.value);setApprovalKey(crypto.randomUUID());}} required/></label><label className="text-sm">Approval duration, hours<input className={field} type="number" min="1" max="720" value={hours} onChange={e=>{setHours(e.target.value);setApprovalKey(crypto.randomUUID());}} required/></label></div><p className="mt-5 text-sm leading-7 text-muted-foreground">This permits payments to the displayed recipient within these limits. Privy constrains each signature; the backend reserves the daily budget. A changed recipient or ownership observation requires another approval.</p><Button className="mt-5" disabled={!!busy||service.status!=='active'}>Approve scope and create Privy wallet</Button></form></section>}
    <section className="mt-10"><h2 className="text-2xl font-medium">3. Fund a wallet and purchase</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{state.approvals.length===0&&<p className="text-sm text-muted-foreground">No approvals yet. Inspect a service to create one.</p>}{state.approvals.map(row=><Card key={row.id}><CardHeader><CardTitle className="flex flex-wrap justify-between gap-3 text-base">{row.approval.name}<Badge variant="outline">{row.state}</Badge></CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{usdc(row.approval.maxAmount)} USDC per purchase · {usdc(row.daily_limit)} USDC daily</p><p className="mt-2 text-xs text-muted-foreground">Expires {new Date(row.approval.expiresAt*1000).toLocaleString()}</p><p className="mt-5 text-xs text-muted-foreground">Fund this payer with Base Sepolia USDC</p><p className="mt-2 break-all font-mono text-xs">{row.payer||'Provisioning incomplete. Retry the same approval.'}</p>{balances[row.id]&&<p className="mt-2 text-sm text-primary">Balance: {balances[row.id]} USDC</p>}<div className="mt-5 flex flex-wrap gap-2">{row.state==='provisioning'&&<Button disabled={!!busy} onClick={()=>run('provision',async()=>{await api({action:'resume-approval',id:row.id});await refresh();})}>Resume wallet setup</Button>}<Button variant="outline" disabled={!!busy||!row.payer} onClick={()=>run('balance',async()=>{const balance=await api<{units:string}>({action:'balance',id:row.id});setBalances(b=>({...b,[row.id]:usdc(balance.units)}));})}>Check balance</Button><Button disabled={!!busy||row.state!=='active'||pending||(!!attempt&&attempt.approvalId!==row.id)} onClick={()=>buy(row.id)}>{attempt?.approvalId===row.id?'Resume same attempt':'Buy once'}</Button><Button variant="ghost" disabled={!!busy||row.state==='revoked'} onClick={()=>run('revoke',async()=>{await api({action:'revoke',id:row.id});await refresh();setNotice('Future purchases revoked. Issued signatures are not cancelled.');})}>Revoke</Button></div></CardContent></Card>)}</div>{pending&&<p className="mt-4 text-sm text-muted-foreground">An attempt needs confirmation. Refresh its status or reconcile its transaction before making another purchase.</p>}</section>
    <section className="mt-10"><h2 className="text-2xl font-medium">4. Follow the decision and payment</h2><div className="mt-5 space-y-4">{state.executions.length===0&&<p className="text-sm text-muted-foreground">Every purchase attempt will appear here, including rejected and uncertain attempts.</p>}{state.executions.map(execution=><details key={execution.id} className="rounded-xl border p-5" open={execution.id===state.executions[0]?.id}><summary className="cursor-pointer text-sm"><Badge variant="outline" className="mr-3">{execution.state}</Badge>{execution.receipt?.reason||'Processing or awaiting reconciliation'}</summary><p className="mt-4 break-all font-mono text-xs text-muted-foreground">Attempt {execution.id}</p><ol className="mt-4 space-y-3">{execution.receipt?.steps.map((step,i)=><li key={i} className="flex gap-3 text-sm"><CheckCircle2 className="mt-1 size-4 shrink-0 text-muted-foreground" aria-hidden="true"/><div><span className="font-medium">{step.stage}</span><p className="mt-1 leading-6 text-muted-foreground">{step.detail}</p></div></li>)}</ol>{execution.receipt?.settlement&&<a className="mt-4 inline-block text-sm text-primary underline" href={`https://sepolia.basescan.org/tx/${execution.receipt.settlement.transaction}`} target="_blank" rel="noreferrer">View settlement transaction</a>}{execution.receipt?.resource&&<pre className="mt-4 max-h-64 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-card p-4 text-xs">{execution.receipt.resource}</pre>}{execution.state==='reserved'&&<Button variant="outline" className="mt-4" disabled={!!busy} onClick={()=>run('cancel',async()=>{await api({action:'cancel',id:execution.id});await refresh();setAttempt(null);sessionStorage.removeItem('ens402-pending-attempt');})}>Cancel unsent attempt</Button>}{['submitting','uncertain'].includes(execution.state)&&<Button variant="outline" className="mt-4" onClick={()=>setReconcileId(execution.id)}>Reconcile this attempt</Button>}</details>)}</div>{reconcileId&&<form className="mt-5 rounded-xl border p-5" onSubmit={event=>{event.preventDefault();void run('reconcile',async()=>{await api({action:'reconcile',id:reconcileId,transaction:tx});await refresh();setAttempt(null);sessionStorage.removeItem('ens402-pending-attempt');setReconcileId('');});}}><label className="text-sm">Base Sepolia transaction hash<input className={field} value={tx} onChange={e=>setTx(e.target.value)} pattern="0x[0-9a-fA-F]{64}" required/></label><Button className="mt-4" disabled={!!busy}>Verify nonce and transfer</Button></form>}</section>
    <section className="mt-14 border-t pt-9"><p className="eyebrow">Merchant controls / native ENSv2 EAC</p><h2 className="mt-4 text-2xl font-medium">Delegate the API URL. Protect payment settings.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Connect the wallet that holds native ENS permissions. Prepare a specific record edit or grant, simulate it, then review the transaction in your wallet.</p><Button variant="outline" className="mt-5" disabled={!!busy} onClick={connectSeller}><Wallet aria-hidden="true"/>{seller?'Reconnect Sepolia wallet':'Connect Sepolia wallet'}</Button>{seller&&<p className="mt-3 break-all font-mono text-xs text-muted-foreground">{seller}</p>}{seller&&<form onSubmit={prepare} className="mt-5 rounded-xl border p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Operation<select className={field} value={operation} onChange={e=>{setOperation(e.target.value);setPlan(null);}}><option value="set">Update record</option><option value="grant">Grant record permission</option><option value="revoke">Revoke record permission</option></select></label><label className="text-sm">Record<select className={field} value={record} onChange={e=>{setRecord(e.target.value);setPlan(null);setValue(e.target.value==='ens402.payment'?JSON.stringify(service?.payment??{},null,2):e.target.value==='ens402.status'?'active':service?.endpoint??'');}}>{['agent-endpoint[x402]','ens402.payment','ens402.status'].map(key=><option key={key}>{key}</option>)}</select></label></div>{operation==='set'?<label className="mt-4 block text-sm">New value<textarea className={`${field} min-h-24 font-mono text-xs`} value={value} onChange={e=>{setValue(e.target.value);setPlan(null);}} required/></label>:<label className="mt-4 block text-sm">Operator wallet address<input className={field} value={operator} onChange={e=>{setOperator(e.target.value);setPlan(null);}} pattern="0x[0-9a-fA-F]{40}" required/></label>}<Button className="mt-5" disabled={!!busy||!name}>Prepare and simulate</Button></form>}{plan&&<div className="mt-5 rounded-xl border border-primary/30 p-5"><p className="text-sm font-medium">{plan.transaction.description}</p><p className="mt-3 text-xs leading-6 text-muted-foreground">{plan.note}{plan.broadTextPermission?' This signer has broad root text permission. Narrow revocation does not remove that permission.':''}</p><details className="mt-4"><summary className="cursor-pointer text-sm">Transaction calldata</summary><pre className="mt-3 overflow-auto text-xs">{JSON.stringify(plan.transaction,null,2)}</pre></details><Button className="mt-5" disabled={!!busy} onClick={sendEns}>Review and submit in wallet</Button></div>}</section>
    </>}
  </div>;
}
