import { writeFile } from "node:fs/promises";
import { config } from "dotenv";
import { createPublicClient, http } from "viem";
import { sepolia } from "viem/chains";
import { journalCandidates } from "./journal";
import { snapshot } from "./snapshot";
config({ path: ".env" });
const rpc = process.env.SEPOLIA_RPC_URL;
const roots = process.env.INDEXER_ROOTS?.split(",").map(x => x.trim()).filter(Boolean);
const from = process.env.INDEXER_FROM_BLOCK;
if (!rpc || !roots?.length || !from || !/^\d+$/.test(from)) throw Error("Set SEPOLIA_RPC_URL, INDEXER_ROOTS and INDEXER_FROM_BLOCK (before root creation)");
const client = createPublicClient({ chain: sepolia, transport: http(rpc), ccipRead: false });
const finalized = await client.getBlock({ blockTag: "finalized" });
const to = process.env.INDEXER_TO_BLOCK ? BigInt(process.env.INDEXER_TO_BLOCK) : finalized.number;
if (to > finalized.number) throw Error("Only finalized snapshots may enter the public catalog");
if (process.env.ENVIO_GRAPHQL_URL && BigInt(from) < 11700000n) throw Error("Envio config starts at 11700000; rebuild it from the requested earlier bound before using journal candidates");
const candidates = process.env.ENVIO_GRAPHQL_URL ? await journalCandidates(process.env.ENVIO_GRAPHQL_URL, to) : undefined;
const catalog = await snapshot(client, { roots, fromBlock: BigInt(from), toBlock: to, candidates });
await writeFile(process.argv[2] || "/tmp/ens402-catalog.json", JSON.stringify(catalog, null, 2) + "\n");
console.log(`Exported ${catalog.services.length} services at finalized block ${to}; ${catalog.excluded.length} exclusions`);
