import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function Architecture() {
  return <article className="section-shell max-w-4xl py-12 sm:py-20">
    <Button asChild variant="ghost" className="-ml-3"><Link href="/"><ArrowLeft aria-hidden="true"/>Back to ENS402</Link></Button>
    <p className="eyebrow mt-9">Architecture / design notes</p><h1 className="mt-4 text-4xl font-medium tracking-tight sm:text-5xl">Public configuration.<br/>Explicit trust boundaries.</h1><p className="mt-6 text-base leading-8 text-muted-foreground">ENS402 is a proposed wallet-independent stack for resolving service configuration, verifying x402 requirements, and consuming risk evidence. It is an independent application design, not an ENS or x402 standard.</p>

    <section className="mt-14 border-t pt-9"><h2 className="text-2xl font-medium">What the core returns</h2><p className="mt-4 leading-7 text-muted-foreground">A resolved service configuration, its observed ENS block and authority evidence, comparison results for the actual HTTP 402, and screening evidence with provider and freshness information. An integrator connects these results to its own approval and signing path. No shared ENS402 buyer database or specific wallet provider is required by the proposed core.</p><p className="mt-4 leading-7 text-muted-foreground">The backend may help observe ENS and protect screening API credentials. It is replaceable infrastructure. Screening results still carry provider trust, and client checks can be bypassed by an agent with an unrestricted key.</p></section>

    <section className="mt-12 border-t pt-9"><h2 className="text-2xl font-medium">Three public records</h2><div className="mt-6 space-y-5">{[
      ['agent-endpoint[x402]', 'The current HTTPS API endpoint. This uses the extension shape of draft ENSIP-26; x402 is our additional protocol value, not a listed standard example.'],
      ['ens402.payment', 'An application-defined JSON record containing version, x402 scheme, network, token contract, and recipient. Treasury controls its writer grant. Per-request prices come from the actual 402.'],
      ['ens402.status', 'An application-defined active or suspended value. Clients interpret the value; writing suspended does not shut down a server or cancel issued payment authorizations.'],
    ].map(([key, explanation]) => <div key={key}><h3 className="break-all font-mono text-sm text-primary">{key}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{explanation}</p></div>)}</div><p className="mt-6 text-sm leading-7 text-muted-foreground">EAC enforces who writes a record, not whether its URL or JSON is valid. Native admin/root and resolver-replacement powers remain relevant. A buyer still needs to establish which service identity it accepts.</p></section>

    <section id="screening" className="mt-12 border-t pt-9"><Badge variant="outline">Documented schema / illustrative decisions</Badge><h2 className="mt-4 text-2xl font-medium">What Intercepta returns</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Quick Scan Address documents a numeric toxicScore and a traits array. Each trait includes risk, name, txsCount, and description. These examples describe how a policy could react; they are not live scan results or provider-recommended thresholds.</p>
      <div className="mt-6 divide-y rounded-xl border bg-card">{[
        ['known_scammer', 'A known-scammer attribution is returned.', 'A policy that treats this confirmed attribution as a blocking risk rejects the payment.'],
        ['sanction_address_communication', 'The address has communication or exposure linked to a sanctioned address.', 'Hold for review under the configured policy. Exposure is not the same as direct sanction attribution.'],
        ['No blocking traits', 'A current, supported scan reports no traits that violate the selected policy.', 'Continue ENS, request, and budget checks. This is not a guarantee of safety or API quality.'],
        ['API error / unsupported evidence', 'No usable result is available.', 'Hold. Do not convert a failed scan into a clean verdict.'],
      ].map(([name, result, action]) => <div key={name} className="p-5"><h3 className="break-all font-mono text-sm text-primary">{name}</h3><p className="mt-2 text-sm text-foreground">{result}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{action}</p></div>)}</div>
      <p className="mt-5 text-sm leading-7 text-muted-foreground">Score ranges and numeric cutoffs require provider confirmation. Address scans, token checks, and authorization scans are separate endpoints. The event uses mainnet risk evidence even with testnet payments; preserve that provenance.</p><a href="https://docs.web3antivirus.io/reference/quick-scan-address" className="mt-3 inline-flex items-center gap-1 text-sm text-primary underline underline-offset-4">Read the provider schema <ArrowUpRight className="size-3.5" aria-hidden="true"/></a>
    </section>

    <section id="reputation" className="mt-12 border-t pt-9"><Badge variant="outline">Future integration</Badge><h2 className="mt-4 text-2xl font-medium">ERC-8004 reputation belongs to an agent identity</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Feedback targets an agentId within an identity registry on a chain. An endpoint can be attached to feedback, and agentWallet is separately managed payment metadata. Neither the current endpoint nor the payee address is the primary reputation identifier.</p>
      <pre className="mt-6 overflow-x-auto rounded-xl border bg-card p-5 font-mono text-xs leading-7 text-primary" aria-label="Conceptual service to agent identity mapping">{`search.dataco.eth  -> registry + agentId 17\nprices.dataco.eth  -> registry + agentId 42\n\ndataco.eth        -> portfolio view of linked services`}</pre>
      <p className="mt-5 text-sm leading-7 text-muted-foreground">This mapping would require verified bindings. A parent-domain portfolio is our possible aggregation design, not native ERC-8004 behavior. Show service-specific evidence and reviewer provenance; do not transfer one child's reputation to its siblings. Name transfers, agent ownership changes, duplicate bindings, and spam feedback need explicit handling.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">ENS organizes names and their identity links. Reputation signals remain attached to ERC-8004 identities. Integrators choose how to score them and select services.</p><a href="https://eips.ethereum.org/EIPS/eip-8004" className="mt-3 inline-flex items-center gap-1 text-sm text-primary underline underline-offset-4">Read ERC-8004 <ArrowUpRight className="size-3.5" aria-hidden="true"/></a>
    </section>

    <section className="mt-12 border-t pt-9"><h2 className="text-2xl font-medium">Wallets and human approval stay composable</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Privy/CDP constrained signing, contract-account delegation, and World-backed reapproval are optional integration paths. A reusable adapter can help an integrator configure its own provider account; it cannot impose a policy on arbitrary existing wallets. The core does not claim global spend enforcement.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">World can verify a returning human when an application requests fresh authentication. The application must still collect exact consent and update the actual permission system. Fresh identity verification alone never authorizes a new payee.</p></section>

    <section id="status" className="mt-12 border-t pt-9"><h2 className="text-2xl font-medium">Implementation status</h2><ul className="mt-5 list-disc space-y-3 pl-5 text-sm leading-7 text-muted-foreground"><li><strong className="text-foreground">Checked on a disposable fork:</strong> native resolver scoped writes, forbidden writes, revocation, record persistence, and root-role override.</li><li><strong className="text-foreground">This website:</strong> landing page, architecture explanation, and explicitly simulated configuration examples.</li><li><strong className="text-foreground">Still to build and verify:</strong> live native service registration and resolution, the reusable SDK, genuine screening calls, and end-to-end testnet payments.</li></ul><p className="mt-5 text-sm leading-7 text-muted-foreground">ENS reads and payment settlement occur on different testnets. They are not atomic, and a later permission change cannot undo an already issued payment signature.</p></section>
  </article>;
}
