import {config} from 'dotenv';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import {createPublicClient,http,encodeFunctionData,encodeDeployData,bytesToHex,keccak256,parseAbi,zeroAddress,type Address} from 'viem';
import {normalize,packetToBytes,labelhash} from 'viem/ens';
import {sepolia} from 'viem/chains';
import {currentDeployment as d,currentRegistryAbi,factoryAbi} from '../packages/sdk/src/ens/index';
config({path:'.env',quiet:true});
const name=normalize(process.env.ENS_PARENT_NAME || ''),owner=process.env.ENS_OWNER_ADDRESS as Address;
if(!name||!/^0x[0-9a-fA-F]{40}$/.test(owner))throw new Error('Set ENS_PARENT_NAME and ENS_OWNER_ADDRESS first');
const client=createPublicClient({chain:sepolia,transport:http(process.env.SEPOLIA_RPC_URL),ccipRead:false});
if(await client.getChainId()!==11155111)throw new Error('Sepolia only');
const labels=name.split('.');let parent:Address=d.rootRegistry;
for(let i=labels.length-1;i>0;i--)parent=await client.readContract({address:parent,abi:currentRegistryAbi,functionName:'getSubregistry',args:[labels[i]!]});
const actual=await client.readContract({address:parent,abi:currentRegistryAbi,functionName:'findOwner',args:[labels[0]!]});
if(actual.toLowerCase()!==owner.toLowerCase())throw new Error('Register the testnet parent to ENS_OWNER_ADDRESS first');
const existing=await client.readContract({address:parent,abi:currentRegistryAbi,functionName:'getSubregistry',args:[labels[0]!]});
if(existing!==zeroAddress)throw new Error('Parent already has a subregistry. Inspect and reuse it deliberately; this planner will not replace it.');
const code=await client.getCode({address:d.factory});if(!code||keccak256(code)!==d.factoryCodeHash)throw new Error('Factory deployment changed');
const salt=BigInt(bytesToHex(randomBytes(32))),initialize=encodeFunctionData({abi:currentRegistryAbi,functionName:'initialize',args:[[{account:owner,roleBitmap:1n|(1n<<128n)}]]});
const deployment=await client.simulateContract({account:owner,address:d.factory,abi:factoryAbi,functionName:'deployProxy',args:[d.registryImplementation,salt,initialize]});
const child=deployment.result;
const nativeAbi=parseAbi(['function setSubregistry(uint256 anyId,address registry)','function findExpiry(string label) view returns(uint64)','function grantRootRoles(uint256 roleBitmap,address account) returns(bool)']);
const parentExpiry=await client.readContract({address:parent,abi:nativeAbi,functionName:'findExpiry',args:[labels[0]!]});
const block=await client.getBlock();const expiry=parentExpiry<block.timestamp+30n*86400n?parentExpiry:block.timestamp+30n*86400n;
if(expiry<=block.timestamp+86400n)throw new Error('Renew the parent before deploying the namespace');
const artifact=JSON.parse(await readFile('contracts/out/ServiceRegistrar.sol/ServiceRegistrar.json','utf8'));
const data=encodeDeployData({abi:artifact.abi,bytecode:artifact.bytecode.object,args:[child,d.factory,d.resolverImplementation,bytesToHex(packetToBytes(name)),expiry]});
const plan={chainId:11155111,name,owner,childRegistry:child,expiry:String(expiry),notes:['No transactions sent. Each operation must be reviewed and signed by the parent owner.','Execute steps 1-3 in order. Record the ServiceRegistrar contract address from its creation receipt.','Step 4 is a template: substitute that address before signing the native registrar grant.','The planner refuses to overwrite an existing subregistry. Parent administrators retain their native powers.'],transactions:[{step:1,to:d.factory,data:encodeFunctionData({abi:factoryAbi,functionName:'deployProxy',args:[d.registryImplementation,salt,initialize]}),value:'0x0',description:'Deploy native UserRegistry; owner gets only registrar and its administration.'},{step:2,to:parent,data:encodeFunctionData({abi:nativeAbi,functionName:'setSubregistry',args:[BigInt(labelhash(labels[0]!)),child]}),value:'0x0',description:'Point the parent at this child registry.'},{step:3,data,value:'0x0',description:'Deploy ServiceRegistrar. Save contractAddress from the receipt.'}],finalGrant:{to:child,function:'grantRootRoles(uint256,address)',roleBitmap:'1',account:'REPLACE_WITH_DEPLOYED_SERVICE_REGISTRAR'},env:{ENS_PARENT_NAME:name,SERVICE_REGISTRAR_ADDRESS:'REPLACE_WITH_DEPLOYED_SERVICE_REGISTRAR'}};
await mkdir('docs/setup',{recursive:true});await writeFile('docs/setup/namespace-transactions.json',JSON.stringify(plan,null,2));console.log('Prepared docs/setup/namespace-transactions.json. No transactions sent.');
